#DEV
spring.profiles.active=development
spring.config.name=development

#STAGING
#spring.profiles.active=staging
#spring.config.name=staging

#RELEASE
#spring.profiles.active=release
#spring.config.name=release
