## spring application name must allign with kubernetes services name
spring.application.name=gtech-hello-service
#spring.cloud.config.uri=http://10.220.37.19:8888

###GENERAL###
server.port=8201

###============ VALIDATION PARAM START ============###
spring.application.time-zone=Asia/Jakarta
spring.application.time-zone-offset=+07:00
spring.jackson.serialization.write-dates-as-timestamps=false
###============ VALIDATION PARAM END ============###


###DATASOURCES###
spring.main.banner-mode=off
logging.level.org.springframework=ERROR
